/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSponsorRouteImport } from './routes/api/sponsor'
import { Route as ApiLabelRouteImport } from './routes/api/label'
import { Route as AuthedSignoutRouteImport } from './routes/_authed.signout'
import { Route as AuthedSponsorsIndexRouteImport } from './routes/_authed.sponsors.index'
import { Route as AuthedMessageIndexRouteImport } from './routes/_authed.message.index'
import { Route as AuthedLabelsIndexRouteImport } from './routes/_authed.labels.index'
import { Route as ApiCronSendMessageRouteImport } from './routes/api/cron/send-message'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSponsorsNewRouteImport } from './routes/_authed.sponsors.new'
import { Route as AuthedMessageSendRouteImport } from './routes/_authed.message.send'
import { Route as AuthedLabelsNewRouteImport } from './routes/_authed.labels.new'
import { Route as AuthedLabelsAssignRouteImport } from './routes/_authed.labels.assign'
import { Route as AuthedChannelChannelRouteImport } from './routes/_authed.channel.$channel'
import { Route as AuthedSponsorsSponsorIdEditRouteImport } from './routes/_authed.sponsors.$sponsorId.edit'
import { Route as AuthedSponsorsSponsorIdDeleteRouteImport } from './routes/_authed.sponsors.$sponsorId.delete'
import { Route as AuthedLabelsLabelIdEditRouteImport } from './routes/_authed.labels.$labelId.edit'
import { Route as AuthedLabelsLabelIdDeleteRouteImport } from './routes/_authed.labels.$labelId.delete'
import { Route as ApiLabelReadableIdLabelIdRemoveRouteImport } from './routes/api/label/$readableId/$labelId/remove'
import { Route as ApiLabelReadableIdLabelIdAddRouteImport } from './routes/api/label/$readableId/$labelId/add'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorRoute = ApiSponsorRouteImport.update({
  id: '/api/sponsor',
  path: '/api/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabelRoute = ApiLabelRouteImport.update({
  id: '/api/label',
  path: '/api/label',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSignoutRoute = AuthedSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSponsorsIndexRoute = AuthedSponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessageIndexRoute = AuthedMessageIndexRouteImport.update({
  id: '/message/',
  path: '/message/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsIndexRoute = AuthedLabelsIndexRouteImport.update({
  id: '/labels/',
  path: '/labels/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCronSendMessageRoute = ApiCronSendMessageRouteImport.update({
  id: '/api/cron/send-message',
  path: '/api/cron/send-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSponsorsNewRoute = AuthedSponsorsNewRouteImport.update({
  id: '/sponsors/new',
  path: '/sponsors/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessageSendRoute = AuthedMessageSendRouteImport.update({
  id: '/message/send',
  path: '/message/send',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsNewRoute = AuthedLabelsNewRouteImport.update({
  id: '/labels/new',
  path: '/labels/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsAssignRoute = AuthedLabelsAssignRouteImport.update({
  id: '/labels/assign',
  path: '/labels/assign',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChannelChannelRoute = AuthedChannelChannelRouteImport.update({
  id: '/channel/$channel',
  path: '/channel/$channel',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSponsorsSponsorIdEditRoute =
  AuthedSponsorsSponsorIdEditRouteImport.update({
    id: '/sponsors/$sponsorId/edit',
    path: '/sponsors/$sponsorId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSponsorsSponsorIdDeleteRoute =
  AuthedSponsorsSponsorIdDeleteRouteImport.update({
    id: '/sponsors/$sponsorId/delete',
    path: '/sponsors/$sponsorId/delete',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLabelsLabelIdEditRoute = AuthedLabelsLabelIdEditRouteImport.update({
  id: '/labels/$labelId/edit',
  path: '/labels/$labelId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLabelsLabelIdDeleteRoute =
  AuthedLabelsLabelIdDeleteRouteImport.update({
    id: '/labels/$labelId/delete',
    path: '/labels/$labelId/delete',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiLabelReadableIdLabelIdRemoveRoute =
  ApiLabelReadableIdLabelIdRemoveRouteImport.update({
    id: '/$readableId/$labelId/remove',
    path: '/$readableId/$labelId/remove',
    getParentRoute: () => ApiLabelRoute,
  } as any)
const ApiLabelReadableIdLabelIdAddRoute =
  ApiLabelReadableIdLabelIdAddRouteImport.update({
    id: '/$readableId/$labelId/add',
    path: '/$readableId/$labelId/add',
    getParentRoute: () => ApiLabelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof AuthedSignoutRoute
  '/api/label': typeof ApiLabelRouteWithChildren
  '/api/sponsor': typeof ApiSponsorRoute
  '/channel/$channel': typeof AuthedChannelChannelRoute
  '/labels/assign': typeof AuthedLabelsAssignRoute
  '/labels/new': typeof AuthedLabelsNewRoute
  '/message/send': typeof AuthedMessageSendRoute
  '/sponsors/new': typeof AuthedSponsorsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/send-message': typeof ApiCronSendMessageRoute
  '/labels/': typeof AuthedLabelsIndexRoute
  '/message/': typeof AuthedMessageIndexRoute
  '/sponsors/': typeof AuthedSponsorsIndexRoute
  '/labels/$labelId/delete': typeof AuthedLabelsLabelIdDeleteRoute
  '/labels/$labelId/edit': typeof AuthedLabelsLabelIdEditRoute
  '/sponsors/$sponsorId/delete': typeof AuthedSponsorsSponsorIdDeleteRoute
  '/sponsors/$sponsorId/edit': typeof AuthedSponsorsSponsorIdEditRoute
  '/api/label/$readableId/$labelId/add': typeof ApiLabelReadableIdLabelIdAddRoute
  '/api/label/$readableId/$labelId/remove': typeof ApiLabelReadableIdLabelIdRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof AuthedSignoutRoute
  '/api/label': typeof ApiLabelRouteWithChildren
  '/api/sponsor': typeof ApiSponsorRoute
  '/channel/$channel': typeof AuthedChannelChannelRoute
  '/labels/assign': typeof AuthedLabelsAssignRoute
  '/labels/new': typeof AuthedLabelsNewRoute
  '/message/send': typeof AuthedMessageSendRoute
  '/sponsors/new': typeof AuthedSponsorsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/send-message': typeof ApiCronSendMessageRoute
  '/labels': typeof AuthedLabelsIndexRoute
  '/message': typeof AuthedMessageIndexRoute
  '/sponsors': typeof AuthedSponsorsIndexRoute
  '/labels/$labelId/delete': typeof AuthedLabelsLabelIdDeleteRoute
  '/labels/$labelId/edit': typeof AuthedLabelsLabelIdEditRoute
  '/sponsors/$sponsorId/delete': typeof AuthedSponsorsSponsorIdDeleteRoute
  '/sponsors/$sponsorId/edit': typeof AuthedSponsorsSponsorIdEditRoute
  '/api/label/$readableId/$labelId/add': typeof ApiLabelReadableIdLabelIdAddRoute
  '/api/label/$readableId/$labelId/remove': typeof ApiLabelReadableIdLabelIdRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authed/signout': typeof AuthedSignoutRoute
  '/api/label': typeof ApiLabelRouteWithChildren
  '/api/sponsor': typeof ApiSponsorRoute
  '/_authed/channel/$channel': typeof AuthedChannelChannelRoute
  '/_authed/labels/assign': typeof AuthedLabelsAssignRoute
  '/_authed/labels/new': typeof AuthedLabelsNewRoute
  '/_authed/message/send': typeof AuthedMessageSendRoute
  '/_authed/sponsors/new': typeof AuthedSponsorsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/send-message': typeof ApiCronSendMessageRoute
  '/_authed/labels/': typeof AuthedLabelsIndexRoute
  '/_authed/message/': typeof AuthedMessageIndexRoute
  '/_authed/sponsors/': typeof AuthedSponsorsIndexRoute
  '/_authed/labels/$labelId/delete': typeof AuthedLabelsLabelIdDeleteRoute
  '/_authed/labels/$labelId/edit': typeof AuthedLabelsLabelIdEditRoute
  '/_authed/sponsors/$sponsorId/delete': typeof AuthedSponsorsSponsorIdDeleteRoute
  '/_authed/sponsors/$sponsorId/edit': typeof AuthedSponsorsSponsorIdEditRoute
  '/api/label/$readableId/$labelId/add': typeof ApiLabelReadableIdLabelIdAddRoute
  '/api/label/$readableId/$labelId/remove': typeof ApiLabelReadableIdLabelIdRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/api/label'
    | '/api/sponsor'
    | '/channel/$channel'
    | '/labels/assign'
    | '/labels/new'
    | '/message/send'
    | '/sponsors/new'
    | '/api/auth/$'
    | '/api/cron/send-message'
    | '/labels/'
    | '/message/'
    | '/sponsors/'
    | '/labels/$labelId/delete'
    | '/labels/$labelId/edit'
    | '/sponsors/$sponsorId/delete'
    | '/sponsors/$sponsorId/edit'
    | '/api/label/$readableId/$labelId/add'
    | '/api/label/$readableId/$labelId/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/api/label'
    | '/api/sponsor'
    | '/channel/$channel'
    | '/labels/assign'
    | '/labels/new'
    | '/message/send'
    | '/sponsors/new'
    | '/api/auth/$'
    | '/api/cron/send-message'
    | '/labels'
    | '/message'
    | '/sponsors'
    | '/labels/$labelId/delete'
    | '/labels/$labelId/edit'
    | '/sponsors/$sponsorId/delete'
    | '/sponsors/$sponsorId/edit'
    | '/api/label/$readableId/$labelId/add'
    | '/api/label/$readableId/$labelId/remove'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/_authed/signout'
    | '/api/label'
    | '/api/sponsor'
    | '/_authed/channel/$channel'
    | '/_authed/labels/assign'
    | '/_authed/labels/new'
    | '/_authed/message/send'
    | '/_authed/sponsors/new'
    | '/api/auth/$'
    | '/api/cron/send-message'
    | '/_authed/labels/'
    | '/_authed/message/'
    | '/_authed/sponsors/'
    | '/_authed/labels/$labelId/delete'
    | '/_authed/labels/$labelId/edit'
    | '/_authed/sponsors/$sponsorId/delete'
    | '/_authed/sponsors/$sponsorId/edit'
    | '/api/label/$readableId/$labelId/add'
    | '/api/label/$readableId/$labelId/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiLabelRoute: typeof ApiLabelRouteWithChildren
  ApiSponsorRoute: typeof ApiSponsorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSendMessageRoute: typeof ApiCronSendMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsor': {
      id: '/api/sponsor'
      path: '/api/sponsor'
      fullPath: '/api/sponsor'
      preLoaderRoute: typeof ApiSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/label': {
      id: '/api/label'
      path: '/api/label'
      fullPath: '/api/label'
      preLoaderRoute: typeof ApiLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/signout': {
      id: '/_authed/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AuthedSignoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sponsors/': {
      id: '/_authed/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof AuthedSponsorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/message/': {
      id: '/_authed/message/'
      path: '/message'
      fullPath: '/message/'
      preLoaderRoute: typeof AuthedMessageIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels/': {
      id: '/_authed/labels/'
      path: '/labels'
      fullPath: '/labels/'
      preLoaderRoute: typeof AuthedLabelsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/cron/send-message': {
      id: '/api/cron/send-message'
      path: '/api/cron/send-message'
      fullPath: '/api/cron/send-message'
      preLoaderRoute: typeof ApiCronSendMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sponsors/new': {
      id: '/_authed/sponsors/new'
      path: '/sponsors/new'
      fullPath: '/sponsors/new'
      preLoaderRoute: typeof AuthedSponsorsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/message/send': {
      id: '/_authed/message/send'
      path: '/message/send'
      fullPath: '/message/send'
      preLoaderRoute: typeof AuthedMessageSendRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels/new': {
      id: '/_authed/labels/new'
      path: '/labels/new'
      fullPath: '/labels/new'
      preLoaderRoute: typeof AuthedLabelsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels/assign': {
      id: '/_authed/labels/assign'
      path: '/labels/assign'
      fullPath: '/labels/assign'
      preLoaderRoute: typeof AuthedLabelsAssignRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/channel/$channel': {
      id: '/_authed/channel/$channel'
      path: '/channel/$channel'
      fullPath: '/channel/$channel'
      preLoaderRoute: typeof AuthedChannelChannelRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sponsors/$sponsorId/edit': {
      id: '/_authed/sponsors/$sponsorId/edit'
      path: '/sponsors/$sponsorId/edit'
      fullPath: '/sponsors/$sponsorId/edit'
      preLoaderRoute: typeof AuthedSponsorsSponsorIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sponsors/$sponsorId/delete': {
      id: '/_authed/sponsors/$sponsorId/delete'
      path: '/sponsors/$sponsorId/delete'
      fullPath: '/sponsors/$sponsorId/delete'
      preLoaderRoute: typeof AuthedSponsorsSponsorIdDeleteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels/$labelId/edit': {
      id: '/_authed/labels/$labelId/edit'
      path: '/labels/$labelId/edit'
      fullPath: '/labels/$labelId/edit'
      preLoaderRoute: typeof AuthedLabelsLabelIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/labels/$labelId/delete': {
      id: '/_authed/labels/$labelId/delete'
      path: '/labels/$labelId/delete'
      fullPath: '/labels/$labelId/delete'
      preLoaderRoute: typeof AuthedLabelsLabelIdDeleteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/label/$readableId/$labelId/remove': {
      id: '/api/label/$readableId/$labelId/remove'
      path: '/$readableId/$labelId/remove'
      fullPath: '/api/label/$readableId/$labelId/remove'
      preLoaderRoute: typeof ApiLabelReadableIdLabelIdRemoveRouteImport
      parentRoute: typeof ApiLabelRoute
    }
    '/api/label/$readableId/$labelId/add': {
      id: '/api/label/$readableId/$labelId/add'
      path: '/$readableId/$labelId/add'
      fullPath: '/api/label/$readableId/$labelId/add'
      preLoaderRoute: typeof ApiLabelReadableIdLabelIdAddRouteImport
      parentRoute: typeof ApiLabelRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSignoutRoute: typeof AuthedSignoutRoute
  AuthedChannelChannelRoute: typeof AuthedChannelChannelRoute
  AuthedLabelsAssignRoute: typeof AuthedLabelsAssignRoute
  AuthedLabelsNewRoute: typeof AuthedLabelsNewRoute
  AuthedMessageSendRoute: typeof AuthedMessageSendRoute
  AuthedSponsorsNewRoute: typeof AuthedSponsorsNewRoute
  AuthedLabelsIndexRoute: typeof AuthedLabelsIndexRoute
  AuthedMessageIndexRoute: typeof AuthedMessageIndexRoute
  AuthedSponsorsIndexRoute: typeof AuthedSponsorsIndexRoute
  AuthedLabelsLabelIdDeleteRoute: typeof AuthedLabelsLabelIdDeleteRoute
  AuthedLabelsLabelIdEditRoute: typeof AuthedLabelsLabelIdEditRoute
  AuthedSponsorsSponsorIdDeleteRoute: typeof AuthedSponsorsSponsorIdDeleteRoute
  AuthedSponsorsSponsorIdEditRoute: typeof AuthedSponsorsSponsorIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSignoutRoute: AuthedSignoutRoute,
  AuthedChannelChannelRoute: AuthedChannelChannelRoute,
  AuthedLabelsAssignRoute: AuthedLabelsAssignRoute,
  AuthedLabelsNewRoute: AuthedLabelsNewRoute,
  AuthedMessageSendRoute: AuthedMessageSendRoute,
  AuthedSponsorsNewRoute: AuthedSponsorsNewRoute,
  AuthedLabelsIndexRoute: AuthedLabelsIndexRoute,
  AuthedMessageIndexRoute: AuthedMessageIndexRoute,
  AuthedSponsorsIndexRoute: AuthedSponsorsIndexRoute,
  AuthedLabelsLabelIdDeleteRoute: AuthedLabelsLabelIdDeleteRoute,
  AuthedLabelsLabelIdEditRoute: AuthedLabelsLabelIdEditRoute,
  AuthedSponsorsSponsorIdDeleteRoute: AuthedSponsorsSponsorIdDeleteRoute,
  AuthedSponsorsSponsorIdEditRoute: AuthedSponsorsSponsorIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiLabelRouteChildren {
  ApiLabelReadableIdLabelIdAddRoute: typeof ApiLabelReadableIdLabelIdAddRoute
  ApiLabelReadableIdLabelIdRemoveRoute: typeof ApiLabelReadableIdLabelIdRemoveRoute
}

const ApiLabelRouteChildren: ApiLabelRouteChildren = {
  ApiLabelReadableIdLabelIdAddRoute: ApiLabelReadableIdLabelIdAddRoute,
  ApiLabelReadableIdLabelIdRemoveRoute: ApiLabelReadableIdLabelIdRemoveRoute,
}

const ApiLabelRouteWithChildren = ApiLabelRoute._addFileChildren(
  ApiLabelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiLabelRoute: ApiLabelRouteWithChildren,
  ApiSponsorRoute: ApiSponsorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSendMessageRoute: ApiCronSendMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
